[package]
name = "saltine"
version = "0.1.0"
authors = ["MrFlynn <nick@pleatsikas.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rust-crypto = "0.2.36"